blank_issues_enabled: false
contact_links:
  - name: Frequently Asked Questions
    url: https://github.com/orgs/CombatCatCommunity/discussions/categories/faq
    about: Check to see if your question is already answered in the FAQ.
  - name: Discord Community
    url: https://discord.gg/WildAssault
    about: Some simple questions can also be answered by our community in Discord.
